---
- name: Install opencivicdata.org
  hosts: opencivicdata-site
  user: ubuntu
  sudo: yes
  roles:
    - role: common-roles/common
      hostname: opencivicdata.org
      extra_packages:
        - libpq-dev
        - unzip
        - gdal-bin
    - role: common-roles/ebs
      device_letter: k
      volume_size: 5
      ebs_path: /projects/opencivicdata.org/
    - role: common-roles/django
      project_name: opencivicdata.org
      git_repositories:
          - repo: "git://github.com/influence-usa/opencivicdata.org.git@disclosures"
            dir: opencivicdata.org
      wsgi_module: data.wsgi:application
    - role: opencivicdata
      project_name: opencivicdata.org
